# Generated by Django 4.1.1 on 2022-10-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="date", field=models.DateField(),
        ),
    ]
